verify tag

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -73,7 +73,12 @@ jobs:
             COMMIT_SHORT=$(git rev-parse --short ${COMMIT})
             RELEASE_TAG="${{ env.NAME }}-${COMMIT_SHORT}"
           fi
-          
+
+          if [[ "${RELEASE_TAG}" =~ "^${{ env.NAME }}" ]]; do
+            echo "Required tag prefix: ${{ env.NAME }}"
+            exit 1
+          fi
+
           git tag ${RELEASE_TAG}
           git push origin tag ${RELEASE_TAG}
 
